# Generated by Django 5.0.4 on 2026-03-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0002_emergencyrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='required_speciality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
