# Generated by Django 5.0.4 on 2026-03-05 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0003_emergencyrequest_required_speciality'),
        ('hospital', '0004_hospitalprofile_specialities'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='previous_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_emergencies', to='hospital.hospitalprofile'),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='rerouted',
            field=models.BooleanField(default=False),
        ),
    ]
