# Generated by Django 5.0.4 on 2026-03-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentrecord',
            name='report_image',
            field=models.ImageField(blank=True, null=True, upload_to='medical_reports/'),
        ),
    ]
