# Generated by Django 5.0.4 on 2026-03-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_remove_hospitalprofile_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
