# Generated by Django 5.0.4 on 2026-03-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_remove_hospitalprofile_address_hospitalprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalprofile',
            name='specialities',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
